config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'xuserx' => "pages#home"

  #get "member/:id" => 'members#show'
  get "members:id",  to: 'members#show', as: 'member'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable


  PROFILE_TITLE = [
    'Admin Manager',
    'Web Designer',
    'Developer',
    'System Manager',
    'Project Manager',
    'C.E.O. Director',
    'Test-User'
  ].freeze

  def name
    "#{first_name} #{last_name}".strip
  end
  def address
    "#{city} ,#{state} ,#{country} ,#{pincode}"
  end
  def self.ransackable_attributes(auth_object = nil)
    ['country', 'city']
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ActionController::Base

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @q = User.ransack(params[:q])
    @users = @q.result.limit(150).order(:created_at)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 " style="background-color: #f7f7f7;margin:0 !important;padding:20px !important;">
  <div class="row" >
    <div class="col-lg6 col-md">
      <small class="d-block mb-3 text-muted">
        Alexjweb@ 2023-2024
      </small>
    </div>
    <div class="col-lg-3">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">About us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">Contact Us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">Our Mission</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-3">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">Blogs</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">Careers</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javscript:void(0)">Profiles</a>
        </li>
      </ul>
    </div>

  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devx</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%#= javascript_importmap_tags %>
</head>

<body class="container-fluid" style="margin:0 !important;padding:0 !important;">


<%= render "layouts/header" %>

<p class="notice" style="margin: 0;padding:0;"><%= notice %> <br><%= alert %></p>

<main class="container">
  <%= yield %>
</main>


<%= render "layouts/footer" %>


</body>
</html>

app/views/members/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devx</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%#= javascript_importmap_tags %>
</head>

<body class="container-fluid" style="margin:0 !important;padding:0 !important;">
<%= render "layouts/header" %>
<main class="container">
  <div class="col-lg-10 mx-auto mt-5">
    <div class="card mb-5">
      <div style="display:flex !important;">
        <div class="col-lg-4">
          <%= image_tag "smiley1.png", class: "iamge-fluid ", style: "max-width:300px;" %>
        </div>
        <div class="lg-8">
          <div class="card-body">
            <h3 class="fw-bold"><%= @user.name %></h3>
            <p class="lead"><%= @user.profile_title %></p>
            <p class="lead text-primary"><%= @user.address %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-5">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <div class="d-flex justyfy-content-start">
            <h3>About</h3>
          </div>
          <div class="col-lg-6">
            <div class="d-flex justyfy-content-start">
<p class="lead"><%= @user.about %></p>
            </div>
          </div>
        </div>
      </div>
    </div>


</main>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<style>
    .imgx {
        width: 120px !important;
        border-radius: 50%;
        border: 2px solid #cdcdcd;
    }
</style>

<div class="col-lg-10 mx-auto mt-5">
  <div class="card mt-4 mb-4">
    <div class="card-body">
      <h3 class="text-center mb-3">Search professional across the world</h3>


      <%= search_form_for @q , url: xuserx_path do |form| %>
        <div class="input-group mb-3">
          <%= form.search_field :country_cont, class: "form-control", placeholder: "Search by country or city",
                                area: { label: "Search area by country o city", describedby: "button-addon2"} %>

          <%= form.submit "Search", class: "btn btn-primary", id: "button-addon2" %>

        </div>
      <% end %>

    </div>
  </div>

  <div class="row mt-4 mb-4">
    <% @users.each do |user| %>
      <div class="col-lg-3 mb-3 mt-3" >
        <div class="card text-center shadow"  style="min-height:200px !important;">
          <div class="card-body">
            <%= image_tag "smiley1.png", style: "width:120px !important; border-radius: 50%; border:2px solid #cdcdcd;", class: "mb-3" %>
          </div>
          <div class="user-info" style="min-height:180px !important;">
            <h5><%= user.name %> </h5>
            <p class="lead"><%= user.profile_title %></p>
            <small class="text-primary"><%= user.country %></small><br>
            <%= link_to "View Profile", member_path(user), class: "btn btn-primary mt-3" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>